// IANA tzdb zone.tab and iso3166.tab (public domain), retrieved 2026-09-11.
// https://github.com/eggert/tz — identifiers only; no fixed UTC offsets.
const institutionTimezones = <(String, String)>[
  ("Afghanistan", "Asia/Kabul"),
  ("Åland Islands", "Europe/Mariehamn"),
  ("Albania", "Europe/Tirane"),
  ("Algeria", "Africa/Algiers"),
  ("Andorra", "Europe/Andorra"),
  ("Angola", "Africa/Luanda"),
  ("Anguilla", "America/Anguilla"),
  ("Antarctica", "Antarctica/Casey"),
  ("Antarctica", "Antarctica/Davis"),
  ("Antarctica", "Antarctica/DumontDUrville"),
  ("Antarctica", "Antarctica/Mawson"),
  ("Antarctica", "Antarctica/McMurdo"),
  ("Antarctica", "Antarctica/Palmer"),
  ("Antarctica", "Antarctica/Rothera"),
  ("Antarctica", "Antarctica/Syowa"),
  ("Antarctica", "Antarctica/Troll"),
  ("Antarctica", "Antarctica/Vostok"),
  ("Antigua & Barbuda", "America/Antigua"),
  ("Argentina", "America/Argentina/Buenos_Aires"),
  ("Argentina", "America/Argentina/Catamarca"),
  ("Argentina", "America/Argentina/Cordoba"),
  ("Argentina", "America/Argentina/Jujuy"),
  ("Argentina", "America/Argentina/La_Rioja"),
  ("Argentina", "America/Argentina/Mendoza"),
  ("Argentina", "America/Argentina/Rio_Gallegos"),
  ("Argentina", "America/Argentina/Salta"),
  ("Argentina", "America/Argentina/San_Juan"),
  ("Argentina", "America/Argentina/San_Luis"),
  ("Argentina", "America/Argentina/Tucuman"),
  ("Argentina", "America/Argentina/Ushuaia"),
  ("Armenia", "Asia/Yerevan"),
  ("Aruba", "America/Aruba"),
  ("Australia", "Antarctica/Macquarie"),
  ("Australia", "Australia/Adelaide"),
  ("Australia", "Australia/Brisbane"),
  ("Australia", "Australia/Broken_Hill"),
  ("Australia", "Australia/Darwin"),
  ("Australia", "Australia/Eucla"),
  ("Australia", "Australia/Hobart"),
  ("Australia", "Australia/Lindeman"),
  ("Australia", "Australia/Lord_Howe"),
  ("Australia", "Australia/Melbourne"),
  ("Australia", "Australia/Perth"),
  ("Australia", "Australia/Sydney"),
  ("Austria", "Europe/Vienna"),
  ("Azerbaijan", "Asia/Baku"),
  ("Bahamas", "America/Nassau"),
  ("Bahrain", "Asia/Bahrain"),
  ("Bangladesh", "Asia/Dhaka"),
  ("Barbados", "America/Barbados"),
  ("Belarus", "Europe/Minsk"),
  ("Belgium", "Europe/Brussels"),
  ("Belize", "America/Belize"),
  ("Benin", "Africa/Porto-Novo"),
  ("Bermuda", "Atlantic/Bermuda"),
  ("Bhutan", "Asia/Thimphu"),
  ("Bolivia", "America/La_Paz"),
  ("Bosnia & Herzegovina", "Europe/Sarajevo"),
  ("Botswana", "Africa/Gaborone"),
  ("Brazil", "America/Araguaina"),
  ("Brazil", "America/Bahia"),
  ("Brazil", "America/Belem"),
  ("Brazil", "America/Boa_Vista"),
  ("Brazil", "America/Campo_Grande"),
  ("Brazil", "America/Cuiaba"),
  ("Brazil", "America/Eirunepe"),
  ("Brazil", "America/Fortaleza"),
  ("Brazil", "America/Maceio"),
  ("Brazil", "America/Manaus"),
  ("Brazil", "America/Noronha"),
  ("Brazil", "America/Porto_Velho"),
  ("Brazil", "America/Recife"),
  ("Brazil", "America/Rio_Branco"),
  ("Brazil", "America/Santarem"),
  ("Brazil", "America/Sao_Paulo"),
  ("Britain (UK)", "Europe/London"),
  ("British Indian Ocean Territory", "Indian/Chagos"),
  ("Brunei", "Asia/Brunei"),
  ("Bulgaria", "Europe/Sofia"),
  ("Burkina Faso", "Africa/Ouagadougou"),
  ("Burundi", "Africa/Bujumbura"),
  ("Cambodia", "Asia/Phnom_Penh"),
  ("Cameroon", "Africa/Douala"),
  ("Canada", "America/Atikokan"),
  ("Canada", "America/Blanc-Sablon"),
  ("Canada", "America/Cambridge_Bay"),
  ("Canada", "America/Creston"),
  ("Canada", "America/Dawson"),
  ("Canada", "America/Dawson_Creek"),
  ("Canada", "America/Edmonton"),
  ("Canada", "America/Fort_Nelson"),
  ("Canada", "America/Glace_Bay"),
  ("Canada", "America/Goose_Bay"),
  ("Canada", "America/Halifax"),
  ("Canada", "America/Inuvik"),
  ("Canada", "America/Iqaluit"),
  ("Canada", "America/Moncton"),
  ("Canada", "America/Rankin_Inlet"),
  ("Canada", "America/Regina"),
  ("Canada", "America/Resolute"),
  ("Canada", "America/St_Johns"),
  ("Canada", "America/Swift_Current"),
  ("Canada", "America/Toronto"),
  ("Canada", "America/Vancouver"),
  ("Canada", "America/Whitehorse"),
  ("Canada", "America/Winnipeg"),
  ("Cape Verde", "Atlantic/Cape_Verde"),
  ("Caribbean NL", "America/Kralendijk"),
  ("Cayman Islands", "America/Cayman"),
  ("Central African Rep.", "Africa/Bangui"),
  ("Chad", "Africa/Ndjamena"),
  ("Chile", "America/Coyhaique"),
  ("Chile", "America/Punta_Arenas"),
  ("Chile", "America/Santiago"),
  ("Chile", "Pacific/Easter"),
  ("China", "Asia/Shanghai"),
  ("China", "Asia/Urumqi"),
  ("Christmas Island", "Indian/Christmas"),
  ("Cocos (Keeling) Islands", "Indian/Cocos"),
  ("Colombia", "America/Bogota"),
  ("Comoros", "Indian/Comoro"),
  ("Congo (Dem. Rep.)", "Africa/Kinshasa"),
  ("Congo (Dem. Rep.)", "Africa/Lubumbashi"),
  ("Congo (Rep.)", "Africa/Brazzaville"),
  ("Cook Islands", "Pacific/Rarotonga"),
  ("Costa Rica", "America/Costa_Rica"),
  ("Côte d’Ivoire", "Africa/Abidjan"),
  ("Croatia", "Europe/Zagreb"),
  ("Cuba", "America/Havana"),
  ("Curaçao", "America/Curacao"),
  ("Cyprus", "Asia/Famagusta"),
  ("Cyprus", "Asia/Nicosia"),
  ("Czech Republic", "Europe/Prague"),
  ("Denmark", "Europe/Copenhagen"),
  ("Djibouti", "Africa/Djibouti"),
  ("Dominica", "America/Dominica"),
  ("Dominican Republic", "America/Santo_Domingo"),
  ("East Timor", "Asia/Dili"),
  ("Ecuador", "America/Guayaquil"),
  ("Ecuador", "Pacific/Galapagos"),
  ("Egypt", "Africa/Cairo"),
  ("El Salvador", "America/El_Salvador"),
  ("Equatorial Guinea", "Africa/Malabo"),
  ("Eritrea", "Africa/Asmara"),
  ("Estonia", "Europe/Tallinn"),
  ("Eswatini (Swaziland)", "Africa/Mbabane"),
  ("Ethiopia", "Africa/Addis_Ababa"),
  ("Falkland Islands", "Atlantic/Stanley"),
  ("Faroe Islands", "Atlantic/Faroe"),
  ("Fiji", "Pacific/Fiji"),
  ("Finland", "Europe/Helsinki"),
  ("France", "Europe/Paris"),
  ("French Guiana", "America/Cayenne"),
  ("French Polynesia", "Pacific/Gambier"),
  ("French Polynesia", "Pacific/Marquesas"),
  ("French Polynesia", "Pacific/Tahiti"),
  ("French S. Terr.", "Indian/Kerguelen"),
  ("Gabon", "Africa/Libreville"),
  ("Gambia", "Africa/Banjul"),
  ("Georgia", "Asia/Tbilisi"),
  ("Germany", "Europe/Berlin"),
  ("Germany", "Europe/Busingen"),
  ("Ghana", "Africa/Accra"),
  ("Gibraltar", "Europe/Gibraltar"),
  ("Greece", "Europe/Athens"),
  ("Greenland", "America/Danmarkshavn"),
  ("Greenland", "America/Nuuk"),
  ("Greenland", "America/Scoresbysund"),
  ("Greenland", "America/Thule"),
  ("Grenada", "America/Grenada"),
  ("Guadeloupe", "America/Guadeloupe"),
  ("Guam", "Pacific/Guam"),
  ("Guatemala", "America/Guatemala"),
  ("Guernsey", "Europe/Guernsey"),
  ("Guinea", "Africa/Conakry"),
  ("Guinea-Bissau", "Africa/Bissau"),
  ("Guyana", "America/Guyana"),
  ("Haiti", "America/Port-au-Prince"),
  ("Honduras", "America/Tegucigalpa"),
  ("Hong Kong", "Asia/Hong_Kong"),
  ("Hungary", "Europe/Budapest"),
  ("Iceland", "Atlantic/Reykjavik"),
  ("India", "Asia/Kolkata"),
  ("Indonesia", "Asia/Jakarta"),
  ("Indonesia", "Asia/Jayapura"),
  ("Indonesia", "Asia/Makassar"),
  ("Indonesia", "Asia/Pontianak"),
  ("Iran", "Asia/Tehran"),
  ("Iraq", "Asia/Baghdad"),
  ("Ireland", "Europe/Dublin"),
  ("Isle of Man", "Europe/Isle_of_Man"),
  ("Israel", "Asia/Jerusalem"),
  ("Italy", "Europe/Rome"),
  ("Jamaica", "America/Jamaica"),
  ("Japan", "Asia/Tokyo"),
  ("Jersey", "Europe/Jersey"),
  ("Jordan", "Asia/Amman"),
  ("Kazakhstan", "Asia/Almaty"),
  ("Kazakhstan", "Asia/Aqtau"),
  ("Kazakhstan", "Asia/Aqtobe"),
  ("Kazakhstan", "Asia/Atyrau"),
  ("Kazakhstan", "Asia/Oral"),
  ("Kazakhstan", "Asia/Qostanay"),
  ("Kazakhstan", "Asia/Qyzylorda"),
  ("Kenya", "Africa/Nairobi"),
  ("Kiribati", "Pacific/Kanton"),
  ("Kiribati", "Pacific/Kiritimati"),
  ("Kiribati", "Pacific/Tarawa"),
  ("Korea (North)", "Asia/Pyongyang"),
  ("Korea (South)", "Asia/Seoul"),
  ("Kuwait", "Asia/Kuwait"),
  ("Kyrgyzstan", "Asia/Bishkek"),
  ("Laos", "Asia/Vientiane"),
  ("Latvia", "Europe/Riga"),
  ("Lebanon", "Asia/Beirut"),
  ("Lesotho", "Africa/Maseru"),
  ("Liberia", "Africa/Monrovia"),
  ("Libya", "Africa/Tripoli"),
  ("Liechtenstein", "Europe/Vaduz"),
  ("Lithuania", "Europe/Vilnius"),
  ("Luxembourg", "Europe/Luxembourg"),
  ("Macau", "Asia/Macau"),
  ("Madagascar", "Indian/Antananarivo"),
  ("Malawi", "Africa/Blantyre"),
  ("Malaysia", "Asia/Kuala_Lumpur"),
  ("Malaysia", "Asia/Kuching"),
  ("Maldives", "Indian/Maldives"),
  ("Mali", "Africa/Bamako"),
  ("Malta", "Europe/Malta"),
  ("Marshall Islands", "Pacific/Kwajalein"),
  ("Marshall Islands", "Pacific/Majuro"),
  ("Martinique", "America/Martinique"),
  ("Mauritania", "Africa/Nouakchott"),
  ("Mauritius", "Indian/Mauritius"),
  ("Mayotte", "Indian/Mayotte"),
  ("Mexico", "America/Bahia_Banderas"),
  ("Mexico", "America/Cancun"),
  ("Mexico", "America/Chihuahua"),
  ("Mexico", "America/Ciudad_Juarez"),
  ("Mexico", "America/Hermosillo"),
  ("Mexico", "America/Matamoros"),
  ("Mexico", "America/Mazatlan"),
  ("Mexico", "America/Merida"),
  ("Mexico", "America/Mexico_City"),
  ("Mexico", "America/Monterrey"),
  ("Mexico", "America/Ojinaga"),
  ("Mexico", "America/Tijuana"),
  ("Micronesia", "Pacific/Chuuk"),
  ("Micronesia", "Pacific/Kosrae"),
  ("Micronesia", "Pacific/Pohnpei"),
  ("Moldova", "Europe/Chisinau"),
  ("Monaco", "Europe/Monaco"),
  ("Mongolia", "Asia/Hovd"),
  ("Mongolia", "Asia/Ulaanbaatar"),
  ("Montenegro", "Europe/Podgorica"),
  ("Montserrat", "America/Montserrat"),
  ("Morocco", "Africa/Casablanca"),
  ("Mozambique", "Africa/Maputo"),
  ("Myanmar (Burma)", "Asia/Yangon"),
  ("Namibia", "Africa/Windhoek"),
  ("Nauru", "Pacific/Nauru"),
  ("Nepal", "Asia/Kathmandu"),
  ("Netherlands", "Europe/Amsterdam"),
  ("New Caledonia", "Pacific/Noumea"),
  ("New Zealand", "Pacific/Auckland"),
  ("New Zealand", "Pacific/Chatham"),
  ("Nicaragua", "America/Managua"),
  ("Niger", "Africa/Niamey"),
  ("Nigeria", "Africa/Lagos"),
  ("Niue", "Pacific/Niue"),
  ("Norfolk Island", "Pacific/Norfolk"),
  ("North Macedonia", "Europe/Skopje"),
  ("Northern Mariana Islands", "Pacific/Saipan"),
  ("Norway", "Europe/Oslo"),
  ("Oman", "Asia/Muscat"),
  ("Pakistan", "Asia/Karachi"),
  ("Palau", "Pacific/Palau"),
  ("Palestine", "Asia/Gaza"),
  ("Palestine", "Asia/Hebron"),
  ("Panama", "America/Panama"),
  ("Papua New Guinea", "Pacific/Bougainville"),
  ("Papua New Guinea", "Pacific/Port_Moresby"),
  ("Paraguay", "America/Asuncion"),
  ("Peru", "America/Lima"),
  ("Philippines", "Asia/Manila"),
  ("Pitcairn", "Pacific/Pitcairn"),
  ("Poland", "Europe/Warsaw"),
  ("Portugal", "Atlantic/Azores"),
  ("Portugal", "Atlantic/Madeira"),
  ("Portugal", "Europe/Lisbon"),
  ("Puerto Rico", "America/Puerto_Rico"),
  ("Qatar", "Asia/Qatar"),
  ("Réunion", "Indian/Reunion"),
  ("Romania", "Europe/Bucharest"),
  ("Russia", "Asia/Anadyr"),
  ("Russia", "Asia/Barnaul"),
  ("Russia", "Asia/Chita"),
  ("Russia", "Asia/Irkutsk"),
  ("Russia", "Asia/Kamchatka"),
  ("Russia", "Asia/Khandyga"),
  ("Russia", "Asia/Krasnoyarsk"),
  ("Russia", "Asia/Magadan"),
  ("Russia", "Asia/Novokuznetsk"),
  ("Russia", "Asia/Novosibirsk"),
  ("Russia", "Asia/Omsk"),
  ("Russia", "Asia/Sakhalin"),
  ("Russia", "Asia/Srednekolymsk"),
  ("Russia", "Asia/Tomsk"),
  ("Russia", "Asia/Ust-Nera"),
  ("Russia", "Asia/Vladivostok"),
  ("Russia", "Asia/Yakutsk"),
  ("Russia", "Asia/Yekaterinburg"),
  ("Russia", "Europe/Astrakhan"),
  ("Russia", "Europe/Kaliningrad"),
  ("Russia", "Europe/Kirov"),
  ("Russia", "Europe/Moscow"),
  ("Russia", "Europe/Samara"),
  ("Russia", "Europe/Saratov"),
  ("Russia", "Europe/Ulyanovsk"),
  ("Russia", "Europe/Volgograd"),
  ("Rwanda", "Africa/Kigali"),
  ("Samoa (American)", "Pacific/Pago_Pago"),
  ("Samoa (western)", "Pacific/Apia"),
  ("San Marino", "Europe/San_Marino"),
  ("Sao Tome & Principe", "Africa/Sao_Tome"),
  ("Saudi Arabia", "Asia/Riyadh"),
  ("Senegal", "Africa/Dakar"),
  ("Serbia", "Europe/Belgrade"),
  ("Seychelles", "Indian/Mahe"),
  ("Sierra Leone", "Africa/Freetown"),
  ("Singapore", "Asia/Singapore"),
  ("Slovakia", "Europe/Bratislava"),
  ("Slovenia", "Europe/Ljubljana"),
  ("Solomon Islands", "Pacific/Guadalcanal"),
  ("Somalia", "Africa/Mogadishu"),
  ("South Africa", "Africa/Johannesburg"),
  ("South Georgia & the South Sandwich Islands", "Atlantic/South_Georgia"),
  ("South Sudan", "Africa/Juba"),
  ("Spain", "Africa/Ceuta"),
  ("Spain", "Atlantic/Canary"),
  ("Spain", "Europe/Madrid"),
  ("Sri Lanka", "Asia/Colombo"),
  ("St Barthelemy", "America/St_Barthelemy"),
  ("St Helena", "Atlantic/St_Helena"),
  ("St Kitts & Nevis", "America/St_Kitts"),
  ("St Lucia", "America/St_Lucia"),
  ("St Maarten (Dutch)", "America/Lower_Princes"),
  ("St Martin (French)", "America/Marigot"),
  ("St Pierre & Miquelon", "America/Miquelon"),
  ("St Vincent", "America/St_Vincent"),
  ("Sudan", "Africa/Khartoum"),
  ("Suriname", "America/Paramaribo"),
  ("Svalbard & Jan Mayen", "Arctic/Longyearbyen"),
  ("Sweden", "Europe/Stockholm"),
  ("Switzerland", "Europe/Zurich"),
  ("Syria", "Asia/Damascus"),
  ("Taiwan", "Asia/Taipei"),
  ("Tajikistan", "Asia/Dushanbe"),
  ("Tanzania", "Africa/Dar_es_Salaam"),
  ("Thailand", "Asia/Bangkok"),
  ("Togo", "Africa/Lome"),
  ("Tokelau", "Pacific/Fakaofo"),
  ("Tonga", "Pacific/Tongatapu"),
  ("Trinidad & Tobago", "America/Port_of_Spain"),
  ("Tunisia", "Africa/Tunis"),
  ("Turkey", "Europe/Istanbul"),
  ("Turkmenistan", "Asia/Ashgabat"),
  ("Turks & Caicos Is", "America/Grand_Turk"),
  ("Tuvalu", "Pacific/Funafuti"),
  ("Uganda", "Africa/Kampala"),
  ("Ukraine", "Europe/Kyiv"),
  ("Ukraine", "Europe/Simferopol"),
  ("United Arab Emirates", "Asia/Dubai"),
  ("United States", "America/Adak"),
  ("United States", "America/Anchorage"),
  ("United States", "America/Boise"),
  ("United States", "America/Chicago"),
  ("United States", "America/Denver"),
  ("United States", "America/Detroit"),
  ("United States", "America/Indiana/Indianapolis"),
  ("United States", "America/Indiana/Knox"),
  ("United States", "America/Indiana/Marengo"),
  ("United States", "America/Indiana/Petersburg"),
  ("United States", "America/Indiana/Tell_City"),
  ("United States", "America/Indiana/Vevay"),
  ("United States", "America/Indiana/Vincennes"),
  ("United States", "America/Indiana/Winamac"),
  ("United States", "America/Juneau"),
  ("United States", "America/Kentucky/Louisville"),
  ("United States", "America/Kentucky/Monticello"),
  ("United States", "America/Los_Angeles"),
  ("United States", "America/Menominee"),
  ("United States", "America/Metlakatla"),
  ("United States", "America/New_York"),
  ("United States", "America/Nome"),
  ("United States", "America/North_Dakota/Beulah"),
  ("United States", "America/North_Dakota/Center"),
  ("United States", "America/North_Dakota/New_Salem"),
  ("United States", "America/Phoenix"),
  ("United States", "America/Sitka"),
  ("United States", "America/Yakutat"),
  ("United States", "Pacific/Honolulu"),
  ("Uruguay", "America/Montevideo"),
  ("US minor outlying islands", "Pacific/Midway"),
  ("US minor outlying islands", "Pacific/Wake"),
  ("Uzbekistan", "Asia/Samarkand"),
  ("Uzbekistan", "Asia/Tashkent"),
  ("Vanuatu", "Pacific/Efate"),
  ("Vatican City", "Europe/Vatican"),
  ("Venezuela", "America/Caracas"),
  ("Vietnam", "Asia/Ho_Chi_Minh"),
  ("Virgin Islands (UK)", "America/Tortola"),
  ("Virgin Islands (US)", "America/St_Thomas"),
  ("Wallis & Futuna", "Pacific/Wallis"),
  ("Western Sahara", "Africa/El_Aaiun"),
  ("Yemen", "Asia/Aden"),
  ("Zambia", "Africa/Lusaka"),
  ("Zimbabwe", "Africa/Harare"),
];
